version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  zookeeper:
    container_name: zookeper
    restart: on-failure
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - back-tier

  kafka:
    container_name: kafka
    restart: on-failure
    image: wurstmeister/kafka:2.11-2.0.1
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "${TOPIC_ID}:1:1,test_${TOPIC_ID}:1:1"
    ports:
      - "9092:9092"
    networks:
      - back-tier
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

# MY SERVICES DEFINITIONS HERE
# ----------------------------
  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka
    environment:
      URL: ${URL_TO_TRACK}
      BOOTSTRAP_SERVER: "${BROKER_IP}:9092"
      TOPIC_ID: ${TOPIC_ID}
      REGEX: "\bfloods?\b"
      FREQUENCY: 30
      DEBUG: 0

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - kafka
    environment:
      DB_URI: ${DB_URI}
      DB_URI_TEST: ${DB_URI_TEST}
      BOOTSTRAP_SERVER: "${BROKER_IP}:9092"
      TOPIC_ID: ${TOPIC_ID}
      DEBUG: 0

  postgres_test:
    container_name: postgres_test
    image: postgres:13-alpine
    hostname: postgres_test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}"
    command: -c fsync=off
# ----------------------------

networks:
  back-tier:
    attachable: true
